### ISSUE TITLE
Stuck at 1%

### ISSUE THREAD

**Issue by mariusmercier** [kazuki-vim/bose-qc45-firmware#1]
Hi, 

First of all, thank you for your work. This is so frustrating that Bose does not offer downgrading after breaking their device.

I started the python script and successfully clicked on "update now", but it doesn't seem to work: it updates until 1% and then stop with the Try Again pop up windows. It seems that the script doesn't detect any files change as I don't see any print statements...

Do you have some idea what could be the problem ? Should we change the option to 3.0.5 in `document.getElementById('smartdevice_targetfirmware').appendChild(new Option('4.0.4-4360+de6a887', '4.0.4'));` ?

Here are my logs: 

```
6/29/2024 22:32:13.454,  Info,       Bose Updater startup ver 7.1.13.5238
6/29/2024 22:32:13.467,  Info,       Loading translations
6/29/2024 22:32:13.467,  Info,       Loaded locale: fr, suffix: fr, result = true
6/29/2024 22:32:13.468,  Info,       Starting web server
6/29/2024 22:32:13.478,  Info,       Listening now
6/29/2024 22:32:13.479,  Info,       Loading settings
6/29/2024 22:32:13.479,  Info,       Creating notification icon
6/29/2024 22:32:13.479,  Info,       Tray available: 1
6/29/2024 22:32:13.550,  Info,       Loaded icon: 1 :/images/favicon.png
6/29/2024 22:32:29.962,  Info,       LOOKUP FILE downloading
6/29/2024 22:32:29.970,  Info,       Starting new session
6/29/2024 22:32:30.023,  Info,       LOOKUP FILE redirecting
6/29/2024 22:32:30.404,  Info,       LOOKUP FILE successfully downloaded.
6/29/2024 22:32:32.103,  Info,       DOWNLOADING INDEX FILE
6/29/2024 22:32:32.513,  Info,       INDEX FILE successfully downloaded.
6/29/2024 22:32:33.351,  Info,       Device version is 4.0.4.4360+de6a887
6/29/2024 22:32:33.351,  Info,       Device original version is 4.0.4-4360+de6a887
6/29/2024 22:32:46.276,  Info,       Update: Waiting for extended challenge -> Idle
6/29/2024 22:41:14.334,  Info,       Beginning update to version 4.0.4
6/29/2024 22:41:14.381,  Info,       Update: Idle -> Downloading firmware
6/29/2024 22:41:15.388,  Info,       DOWNLOADING_FIRMWARE - DONE
6/29/2024 22:41:15.388,  Info,       Reset Update
6/29/2024 22:41:16.456,  Info,       Update: Downloading firmware -> Get device state
6/29/2024 22:41:17.470,  Info,       Update: Get device state -> Synchronize get
6/29/2024 22:41:18.487,  Info,       Update: Synchronize get -> Init start
6/29/2024 22:41:19.477,  Error,      Exception caught:
6/29/2024 22:41:19.480,  Error,      Dumping crash to C:\Users\<username>\AppData\Local\Temp\BoseUpdater_20240629_224119.dmp
```

**Comment by mariusmercier** [comment]
It worked by using: `document.getElementById('smartdevice_targetfirmware').appendChild(new Option('4.0.4', '4.0.4-4360+de6a887'));` :) 

But downgrading didn't fix the sound issue sadly :(

**Comment by kazuki-vim** [comment]
Thank you for pointing out, I appreciate it !
When trying, I used `document.getElementById('smartdevice_targetfirmware').appendChild(new Option('4.0.4-4360+de6a887', '4.0.4-4360+de6a887'));`
But I edited it wrong in Readme file.

About sound issue, actually I don't have any Windows device at home so I leave my Bose QC45 in office. Hence, I couldn't test it after downgrading yet. Will get back to you tomorrow.

But it's sad that you said the sound issue is not fixed, then probably firmware 4.0.4 did some serious damages to the headphone.

Can you at least try to update to 4.0.4 again?

**Comment by mariusmercier** [comment]
Hi ! 

I am was looking for downloading previous firmware: I found [3.0.2-3763+010f98](https://www.reddit.com/r/bose/comments/zrhaey/multiple_questions_from_new_qc45_owner/) or [3.0.2-3763+0120f98](https://www.reddit.com/r/bose/comments/10fxnb8/qc45_right_side_louder_no_matter_what_i_do/), and 
[2.0.4-3475+32e4b0e](https://www.reddit.com/r/bose/comments/10fxnb8/qc45_right_side_louder_no_matter_what_i_do/). But I can't download any of them with `https://downloads.bose.com/ced/duran/duran_encrypted_prod_<version>-<hash>.bin`...

Maybe it could be worth to try some brute force by testing various hashes with a script?

**Comment by kazuki-vim** [comment]
It's really helpful!
I've been trying to find information of 3.0.2 & 2.0.4 all over the internet but couldn't. Can't believe you could find 2 threads!

From information you gave me, yeah I tried to download but it also didn't work.
I'm suspecting they either hosted them with different name, or removed them already.

Let me see if I can do something.

**Comment by mariusmercier** [comment]
I looked a bit at https://downloads.bose.com/lookup.xml to see if I could find the release for the QC 2023, it seems to be this: https://downloads.bose.com/ced/prince/index.xml but not release info sadly

I was hoping that something like `https://downloads.bose.com/ced/prince/prince_encrypted_prod_1.0.6-f5f219b.bin` would work, but no

**Comment by kazuki-vim** [comment]
If you have time, can you help me get the bin file? 
The process should be the same, append the latest option (1.0.8-xxxxx), except not run python script. 
Then you can find the original binary with name `Bose Updater.xxx`.
Your Bose SC will be flashed with latest firmware so it should be safe. 

But then it's weird that firmware doesn't exist in xml file but could be downloaded and flashed

**Comment by kazuki-vim** [comment]
> I looked a bit at https://downloads.bose.com/lookup.xml to see if I could find the release for the QC 2023, it seems to be this: https://downloads.bose.com/ced/prince/index.xml but not release info sadly
> 
> I was hoping that something like `https://downloads.bose.com/ced/prince/prince_encrypted_prod_1.0.6-f5f219b.bin` would work, but no

I tried to look through firmware that other Bose devices use. The name pattern should remain, but looks like they removed the old versions (I couldn't download old version of other devices also), hence people need to back it up before the new version is release

**Comment by kazuki-vim** [comment]
Updated:
I tried my headphone with downgraded firmware but issue is not fixed, as you said ealier. 
From Bose Connect application, it looks like they removed 4.0.4 firmware update, because they said "Your product is up to date" meanwhile headphone is on 3.5.0
If the firmware can't fix the issue, I don't know what else can fix..

![image](https://github.com/kazuki-vim/bose-qc45-firmware/assets/172467905/dac99fbd-d423-40ca-b52b-5d123b2af628)

**Comment by mariusmercier** [comment]
That's strange, I was able to upgrade it again to 4.0.4. I did it both through the app and through the btu.bose.com but this didn't fix the sound issue anyway. I will try to see with the customer service this week if I can have a replacement, but as I am out of warranty this is unlikely. 

I am a bit hesitant to flash the QC 2023, even if the risk is low. I don't want to break it 😅

**Comment by mariusmercier** [comment]
Thanks again for your help, even if it didn't solve the issue, it is great to know that we can downgrade our firmware !

**Comment by kazuki-vim** [comment]
Thanks for your great cooperation! 
My headphone is also out of warranty, and Bose Suppport "offered" me a replacement with full price :D 
That's why I've been trying so hard to revive it.

I will continue trying, maybe investigate lower level (bluetooth transmit, eletrical signal) to find out what they did with software but (possibly) broke the hardware level, to a point that old software couldn't do anything 

Once again, thank you. 
I still maintain this project, in case I'm rich enough to buy another QC45 haha

**Comment by kazuki-vim** [comment]
FYI I found a way to download `2.0.4-32e4b0e` firmware, since it's still the latest version in China
```
<INDEX REVISION="01.00.00">
<DEVICE ID="0x4039" PRODUCTNAME="Quietcomfort 45" USE_CLOUD="0">
<HARDWARE REVISION="01.00.00">
<RELEASE HTTPHOST="www.bose.cn" LANGUAGES="en-us,es-mx,de,it,fr,zh-cn,nl,ja,pt-br,ru,pl" REVISION="2.0.4-32e4b0e" URLPATH="/ced/bose_music_china/duran/">
<IMAGE CRC="0xFCC05C1B" FILENAME="duran_encrypted_prod_2.0.4-32e4b0e.bin" LENGTH="6018444" NOFORCE="1" REVISION="2.0.4-32e4b0e" SUBID="0"/>
</RELEASE>
</HARDWARE>
</DEVICE>
</INDEX>
```
I will try to flash it now 
![image](https://github.com/kazuki-vim/bose-qc45-firmware/assets/172467905/ba2f6afa-6533-4d75-bf7f-3f1cac4784bf)

**Comment by mariusmercier** [comment]
Oh ! Very nice ! Finger crossed for the sound 🤞

**Comment by kazuki-vim** [comment]
Updated:
Unfortunatelly it is still not fixed. When flashing 2.0.4 the headphone bluetooth mode is not even turned on (no light at all)
Tried to flash 3.5.0 and 4.0.4 it went back to normal (can connect via Bluetooth but no sound)

I'm not sure if any differences in Hardware level between China version and Global version that cause the incompatibility when using China's firmware.

I will upload `2.0.4` later, in case you want to try

**Comment by kazuki-vim** [comment]
Uploaded 2.0.4
