### ISSUE TITLE
WHY ERROR PLS

### ISSUE THREAD

**Issue by modest-x** [kazuki-vim/bose-qc45-firmware#3]
![屏幕截图 2024-09-23 143312](https://github.com/user-attachments/assets/2e7b3930-36cf-4014-b342-36818dcf567d)
why can not run？ PLS
![屏幕截图 2024-09-23 143312](https://github.com/user-attachments/assets/a1e3b320-052f-410d-974c-bbddcddff06a)

**Comment by valievkarim** [comment]
You need to put the path to chosen firmware file into the command line argument of the script
i.e. put the firmware file to c:\duran_encrypted_prod_1.0.3-ee3f55e.bin
and then run like this:
`py ./main.py c:\duran_encrypted_prod_1.0.3-ee3f55e.bin`

**Comment by modest-x** [comment]
SO SMART
