### ISSUE TITLE
stuck at part 2

### ISSUE THREAD

**Issue by cleeelee** [kazuki-vim/bose-qc45-firmware#5]
The error description is as follows
![image](https://github.com/user-attachments/assets/29238259-1e36-4696-a9a7-eb877ce858ba)
I made adjustments according to the questions posted by modest-x. The file exists in the path, but the error still occurs...

**Comment by kazuki-vim** [comment]
which python version you're using sir?

**Comment by cleeelee** [comment]
> 先生，您使用的是哪个版本的 Python？

I am using 3.13, and the plugin version in vscode is
v2024.20.0

**Comment by cleeelee** [comment]
> which python version you're using sir?

Your words about Python versions inspired me, so I reinstalled an older version: 3.12.4, and it worked quite smoothly! As someone who doesn't know much about computer code, I encountered too many troubles in it, but the ending is good, thanks to you and the github project you created!
![Screenshot_20241114_234747](https://github.com/user-attachments/assets/d4fe2b67-9da6-435d-bea9-cdaa80e4f5a4)

**Comment by kazuki-vim** [comment]
Thank you for these warm words!
I will take a note for maximum allowed Python version.
Sorry I've been busy these days so I couldn't make time to help you check.
